import Foundation

/// The files `fuzz-init` writes, the manifest stanza it prints, and the rules
/// for what may be called a fuzz target.
///
/// Kept free of `PackagePlugin` so the test target can compile it: a plugin
/// target cannot be imported, so `Tests/FuzzInitPluginTests` symlinks this file
/// and builds it a second time.
enum Scaffold {
    /// The C entry point for the paired shape.
    ///
    /// Byte-identical for every target — it names only the two symbols
    /// `FuzzTargetPlugin` generates — which is exactly why hand-copying it is
    /// worth automating.
    static let shim = """
        /* Generated by `swift package fuzz-init`. You should never need to edit this.
         *
         * The fuzz executable is deliberately pure C. SwiftPM's native build system
         * renames a *Swift* executable target's `main` to `<Module>_main` and aliases
         * `main` to it, which collides with the `main` libFuzzer's runtime provides. A
         * C target has no Swift `main` to rename, so the collision never arises and
         * this builds under both build systems.
         *
         * Both symbols below come from the fuzz target's Swift library, via the file
         * swift-fuzz's FuzzTargetPlugin generates.
         */
        #include <inttypes.h>
        #include <stddef.h>

        int swift_fuzz_run(const uint8_t *data, size_t size);
        void swift_fuzz_initialize(void);

        int LLVMFuzzerInitialize(int *argc, char ***argv) {
          (void)argc;
          (void)argv;
          swift_fuzz_initialize();
          return 0;
        }

        int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
          return swift_fuzz_run(data, size);
        }

        """

    /// The harness the user actually edits.
    static func harness(target: String) -> String {
        """
        import Fuzzing
        // TODO: import the library you are testing, and add it to this target's
        // dependencies in Package.swift.

        let fuzzTargets: @Sendable () -> Void = {
            FuzzTarget("\(target)") { bytes in
                // `bytes` is a `Span<UInt8>` holding one fuzzer-produced input:
                // arbitrary, usually malformed, and valid only for this call.
                // It is bounds-checked and cannot escape, so nothing here needs
                // `unsafe`. Copy anything you want to keep.
                //
                // Expected failures should be swallowed — `try?` a throwing
                // parser. Anything that gets past that (a trap, a precondition
                // failure, an overflow, unbounded recursion) is a finding, which
                // is the point.
                //
                // TODO: call the code under test, for example:
                // _ = try? MyParser.parse(bytes)
                _ = bytes
            }
        }

        """
    }

    /// The manifest entries to paste in. Editing `Package.swift` automatically
    /// would mean parsing and rewriting arbitrary Swift, so this is printed
    /// rather than applied.
    static func manifestStanza(target: String, standalone: Bool) -> String {
        if standalone {
            return """
                .executableTarget(
                    name: "\(target)",
                    dependencies: [
                        .product(name: "Fuzzing", package: "swift-fuzz"),
                        // .product(name: "<YourLibrary>", package: "<YourRepoDirectory>"),
                    ],
                    path: "FuzzTargets/\(target)",
                    plugins: [.plugin(name: "FuzzTargetPlugin", package: "swift-fuzz")]
                ),
                """
        }
        return """
            .executableTarget(
                name: "\(target)",
                dependencies: ["\(target)Target"],
                path: "FuzzTargets/\(target)Shim"
            ),
            .target(
                name: "\(target)Target",
                dependencies: [
                    .product(name: "Fuzzing", package: "swift-fuzz"),
                    // .product(name: "<YourLibrary>", package: "<YourRepoDirectory>"),
                ],
                path: "FuzzTargets/\(target)",
                plugins: [.plugin(name: "FuzzTargetPlugin", package: "swift-fuzz")]
            ),
            """
    }

    /// Whether `name` can be a SwiftPM target, a module and a directory.
    ///
    /// Checked before anything is written, so a bad name fails cleanly rather
    /// than leaving half a target behind for the user to delete.
    static func validate(name: String) throws {
        guard !name.isEmpty else {
            throw FuzzInitError("The target name cannot be empty.")
        }
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_"))
        guard name.unicodeScalars.allSatisfy(allowed.contains),
              let first = name.first, first.isLetter || first == "_"
        else {
            throw FuzzInitError("""
                "\(name)" is not usable as a target name. Use letters, digits and \
                underscores, starting with a letter.
                """)
        }
    }
}

struct FuzzInitError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}
