import Foundation
import PackagePlugin

/// Generates the bridge between the C entry-point shim and the user's
/// `fuzzTargets` closure.
///
/// The generated code exists for two reasons. It gives the C shim two stable
/// symbols to call, and — more subtly — it *references* `fuzzTargets`. A
/// top-level `let` in Swift is initialised lazily, so a `fuzzTargets` closure
/// that nothing ever mentions would never run, and no target would register.
@main
struct FuzzTargetPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let work = context.pluginWorkDirectoryURL
        let staged = work.appending(path: "FuzzEntryPoint.staged.swift")
        let output = work.appending(path: "FuzzEntryPoint.swift")

        try Self.source.write(to: staged, atomically: true, encoding: .utf8)

        // The file is produced above, at manifest-evaluation time; the copy is
        // what tells SwiftPM about it and gets it compiled into the target.
        return [
            .buildCommand(
                displayName: "Generating fuzz entry point for \(target.name)",
                executable: URL(fileURLWithPath: "/bin/cp"),
                arguments: [staged.path, output.path],
                inputFiles: [staged],
                outputFiles: [output]
            )
        ]
    }

    static let source = """
        // Generated by swift-fuzz. Do not edit.
        //
        // `swift_fuzz_initialize` and `swift_fuzz_run` are called by the C entry-point
        // shim, which supplies libFuzzer's `LLVMFuzzerInitialize` and
        // `LLVMFuzzerTestOneInput`.
        import Fuzzing

        @_cdecl("swift_fuzz_initialize")
        func swift_fuzz_initialize() {
            // Touching `fuzzTargets` is what forces the lazy global to initialise,
            // which is what actually registers the targets.
            fuzzTargets()
            FuzzRunner.initialize()
        }

        @_cdecl("swift_fuzz_run")
        func swift_fuzz_run(_ data: UnsafeRawPointer?, _ size: Int) -> CInt {
            FuzzRunner.run(data, size)
        }

        """
}
