import Foundation

/// The three files an OSS-Fuzz submission needs, generated from this package.
///
/// Kept free of `PackagePlugin` so the test target can compile it — plugin
/// targets cannot be imported.
enum OSSFuzzTemplates {
    /// The build script OSS-Fuzz runs inside its builder image.
    ///
    /// Note it uses plain `swift build`, not `swift package fuzz`: OSS-Fuzz
    /// supplies its own flags through `$SWIFTFLAGS` and never runs our command
    /// plugin. That works because the executable target is C, so the
    /// graph-wide `-parse-as-library` in `$SWIFTFLAGS` is harmless.
    static func buildScript(packageDirectory: String, targets: [String]) -> String {
        """
        #!/bin/bash -eu
        # Generated by `swift package generate-oss-fuzz-script`.
        #
        # `precompile_swift` (from the base-builder-swift image) exports $SWIFTFLAGS,
        # which carries -sanitize=fuzzer,$SANITIZER and static linking. OSS-Fuzz builds
        # with plain `swift build` — swift-fuzz's command plugin is not involved.

        . precompile_swift

        cd \(packageDirectory)
        swift build -c release $SWIFTFLAGS

        for target in \(targets.joined(separator: " ")); do
          cp ".build/release/$target" "$OUT/$target"

          # Seeds and corpus ship together as the starting corpus. Using `find`
          # rather than a glob so an empty or missing directory is not an error.
          if find "Seeds/$target" "Corpus/$target" -type f -print0 2>/dev/null | grep -qz .; then
            find "Seeds/$target" "Corpus/$target" -type f -print0 2>/dev/null \\
              | xargs -0 zip -q -j "$OUT/${target}_seed_corpus.zip"
          fi

          if [ -f "Dictionaries/$target.dict" ]; then
            cp "Dictionaries/$target.dict" "$OUT/$target.dict"
          fi
        done

        """
    }

    /// Only `address` and `thread` are supported for Swift — not `undefined`.
    static func projectYAML(repository: String) -> String {
        """
        homepage: "\(repository)"
        main_repo: "\(repository)"
        language: swift
        primary_contact: "" # TODO: an email address OSS-Fuzz can reach you on
        fuzzing_engines:
          - libfuzzer
        sanitizers:
          - address
          - thread

        """
    }

    static func dockerfile(repository: String, checkoutName: String) -> String {
        """
        FROM gcr.io/oss-fuzz-base/base-builder-swift

        RUN git clone --depth 1 \(repository) \(checkoutName)
        COPY build.sh $SRC
        WORKDIR $SRC/\(checkoutName)

        """
    }

    static func readme(targets: [String], directory: String) -> String {
        """
        # OSS-Fuzz integration

        Generated by `swift package generate-oss-fuzz-script`. Regenerate it after
        adding or renaming a fuzz target — the target list below is baked into
        `build.sh`:

        \(targets.map { "- `\($0)`" }.joined(separator: "\n"))

        ## Submitting

        Copy these three files into a new directory in a checkout of
        [google/oss-fuzz](https://github.com/google/oss-fuzz) under `projects/<name>/`,
        fill in the TODOs in `project.yaml`, and open a pull request.

        Test the build locally first, from your oss-fuzz checkout:

        ```bash
        python infra/helper.py build_image <name>
        python infra/helper.py build_fuzzers --sanitizer address <name>
        python infra/helper.py check_build <name>
        python infra/helper.py run_fuzzer <name> \(targets.first ?? "<target>")
        ```

        ## What the build does

        OSS-Fuzz builds with plain `swift build` and its own `$SWIFTFLAGS`; the
        `swift package fuzz` plugin is not involved. `build.sh` therefore has to
        reproduce what the plugin normally arranges: it builds `\(directory)/`, copies
        each fuzz executable into `$OUT`, and packages `Seeds/` plus `Corpus/` as
        `<target>_seed_corpus.zip` and `Dictionaries/<target>.dict` alongside it.

        Note OSS-Fuzz supports only the `address` and `thread` sanitizers for Swift.

        """
    }

    /// Turns whatever `git remote get-url` reports into a URL OSS-Fuzz's
    /// Dockerfile can clone anonymously.
    ///
    /// Remotes are commonly SSH (`git@github.com:owner/repo.git`), which the
    /// builder cannot use — it has no credentials. The `.git` suffix is dropped
    /// too, so the derived checkout directory is `repo` rather than `repo.git`.
    static func normalizeRemote(_ remote: String) -> String? {
        var url = remote.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !url.isEmpty else { return nil }

        // `ssh://` is checked before the scp-style form: it also contains `@`,
        // but its path is separated by `/`, not `:`.
        if url.hasPrefix("ssh://") {
            var rest = String(url.dropFirst("ssh://".count))
            if let at = rest.firstIndex(of: "@") {
                rest = String(rest[rest.index(after: at)...])
            }
            url = "https://" + rest
        } else if !url.hasPrefix("http"), let at = url.firstIndex(of: "@") {
            // scp-style: [user@]host:path
            let hostAndPath = String(url[url.index(after: at)...])
            guard let colon = hostAndPath.firstIndex(of: ":") else { return nil }
            let host = String(hostAndPath[..<colon])
            let path = String(hostAndPath[hostAndPath.index(after: colon)...])
            url = "https://\(host)/\(path)"
        }

        if url.hasSuffix(".git") { url.removeLast(4) }
        guard url.hasPrefix("http") else { return nil }
        return url
    }

    /// The directory name a clone of `repository` lands in.
    static func checkoutName(for repository: String) -> String {
        let trimmed = repository.hasSuffix("/") ? String(repository.dropLast()) : repository
        let name = trimmed.split(separator: "/").last.map(String.init) ?? "REPO"
        return name.hasSuffix(".git") ? String(name.dropLast(4)) : name
    }
}
