extension OSSFuzzTemplates {
    static let exporter = #"""
    #!/usr/bin/env python3
    # Generated by swift-fuzz. Build-time only; exported fuzzers are native ELF files.
    import configparser
    import hashlib
    import json
    import os
    from pathlib import Path
    import re
    import shlex
    import shutil
    import subprocess
    import sys
    import tempfile
    import zipfile

    NAME = re.compile(r'[A-Za-z_][A-Za-z0-9_-]{0,127}\Z', re.ASCII)
    RESERVED = {'llvm-symbolizer', 'llvm-symbolizer-swift'}

    def checked_names(names):
        seen = set()
        for name in names:
            if not NAME.fullmatch(name) or name.lower() in RESERVED:
                raise ValueError('Invalid or reserved fuzz target name: ' + repr(name))
            if name.lower() in seen:
                raise ValueError('Duplicate fuzz target name (ignoring case): ' + name)
            seen.add(name.lower())
        return names

    def package_inputs(package, target, destination, include_corpus):
        inputs = {}
        roots = ['Seeds', 'Corpus'] if include_corpus else ['Seeds']
        for root in roots:
            directory = package / root / target
            if not directory.is_dir() or (package / root).is_symlink() or directory.is_symlink():
                continue
            for path in sorted(directory.rglob('*')):
                relative = path.relative_to(directory)
                if any(part.startswith('.') for part in relative.parts):
                    continue
                if path.is_symlink() or any((directory.joinpath(*relative.parts[:i])).is_symlink() for i in range(1, len(relative.parts))):
                    continue
                if path.is_file():
                    data = path.read_bytes()
                    inputs[hashlib.sha256(data).hexdigest()] = data
        if not inputs:
            return
        with zipfile.ZipFile(destination / (target + '_seed_corpus.zip'), 'w', zipfile.ZIP_DEFLATED) as archive:
            for name, data in sorted(inputs.items()):
                info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, data)

    def package_options(package, target, destination):
        options = configparser.ConfigParser(interpolation=None)
        custom = package / 'Options' / (target + '.options')
        if custom.is_file():
            options.read(custom)
        if not options.has_section('libfuzzer'):
            options.add_section('libfuzzer')
        section = options['libfuzzer']
        for key, value in {'use_value_profile': '1', 'detect_leaks': '0'}.items():
            if key not in section:
                section[key] = value
        dictionary = package / 'Dictionaries' / (target + '.dict')
        if dictionary.is_file():
            shutil.copyfile(dictionary, destination / dictionary.name)
            if 'dict' not in section:
                section['dict'] = dictionary.name
        with (destination / (target + '.options')).open('w') as stream:
            options.write(stream)

    def build(config, source, output, work):
        if os.environ.get('FUZZING_ENGINE', 'libfuzzer') != 'libfuzzer':
            raise ValueError('Swift export supports the libfuzzer engine.')
        sanitizer = os.environ.get('SANITIZER', 'address')
        if sanitizer not in ('address', 'thread', 'coverage'):
            raise ValueError('Swift export supports address, thread and coverage builds.')
        if os.environ.get('ARCHITECTURE', 'x86_64') != 'x86_64':
            raise ValueError('This generated toolchain supports x86_64; configure a matching toolchain before adding architectures.')
        if config.get('version') != 1:
            raise ValueError('Unsupported swift-fuzz configuration version.')
        checkout = (source / config['checkout']).resolve()
        if checkout.parent != source.resolve():
            raise ValueError('The checkout must be a direct child of SRC.')
        package = (checkout / config['package']).resolve()
        if package != checkout.resolve() and checkout.resolve() not in package.parents:
            raise ValueError('The package path must stay inside the cloned repository.')
        products = config['products']
        if not products or len(products) != len(set(products)):
            raise ValueError('No products, or duplicate products, in the build configuration.')
        flags = shlex.split(os.environ.get('SWIFTFLAGS', ''))
        if not flags:
            raise ValueError('SWIFTFLAGS is empty: source precompile_swift in build.sh first.')
        output.mkdir(parents=True, exist_ok=True)
        work.mkdir(parents=True, exist_ok=True)
        scratch = work / ('swift-fuzz-' + sanitizer)
        # Static Swift initializes its crash handler in a normal C++ constructor.
        # Run first so libFuzzer retains signal handling and writes crash inputs.
        # No sanitizer options supplied by OSS-Fuzz are changed.
        initializer = work / 'swift-fuzz-runtime.c'
        initializer.write_text('''#include <stdlib.h>
    __attribute__((constructor(101))) static void swift_fuzz_environment(void) {
      setenv("SWIFT_BACKTRACE", "enable=no", 1);
    }
    ''')
        runtime = work / 'swift-fuzz-runtime.o'
        subprocess.run(shlex.split(os.environ.get('CC', 'clang')) + ['-fPIC', '-c', str(initializer), '-o', str(runtime)], check=True)
        flags += ['-Xlinker', str(runtime)]
        base = ['swift', 'build', '--package-path', str(package), '--scratch-path', str(scratch), '-c', 'release'] + flags
        for product in products:
            subprocess.run(base + ['--product', product], check=True)
        binary_directory = Path(subprocess.check_output(base + ['--show-bin-path'], text=True).strip())
        environment = dict(os.environ, FUZZ_LIST_TARGETS='1', SWIFT_BACKTRACE='enable=no')
        environment.pop('FUZZ_TARGET', None)
        # Discovery is bookkeeping, not a leak check. Real executions retain the
        # sanitizer environment chosen by OSS-Fuzz and the per-target options.
        environment['ASAN_OPTIONS'] = environment.get('ASAN_OPTIONS', '') + ':detect_leaks=0'
        targets = []
        for product in products:
            binary = binary_directory / product
            result = subprocess.run([str(binary)], env=environment, text=True, stdout=subprocess.PIPE, check=True, timeout=60)
            names = result.stdout.splitlines()
            if not names:
                raise ValueError('No fuzz registrations reported by ' + product)
            checked_names(names)
            targets.extend({'product': product, 'target': name} for name in names)
        checked_names([entry['target'] for entry in targets])
        # Stage every artifact before replacing any earlier export.
        with tempfile.TemporaryDirectory(prefix='.swift-fuzz-', dir=output) as temporary:
            staging = Path(temporary)
            for entry in targets:
                target, product = entry['target'], entry['product']
                binary = binary_directory / product
                with binary.open('rb') as stream:
                    signature = stream.read(4)
                if signature != b'\x7fELF':
                    raise ValueError('Expected a native ELF executable: ' + str(binary))
                shutil.copyfile(binary, staging / target)
                (staging / target).chmod(0o755)
                package_inputs(package, target, staging, config['include_corpus'])
                package_options(package, target, staging)
            # SwiftPM resolves Bundle.module relative to the executable when
            # the original build directory no longer exists.
            for resource in binary_directory.iterdir():
                if resource.is_dir() and resource.suffix in ('.resources', '.bundle'):
                    shutil.copytree(resource, staging / resource.name)
            manifest = output / 'swift-fuzz-targets.json'
            old = json.loads(manifest.read_text()) if manifest.exists() else []
            checked_names([entry['target'] for entry in old])
            for entry in old:
                for suffix in ('', '.dict', '.options', '_seed_corpus.zip'):
                    (output / (entry['target'] + suffix)).unlink(missing_ok=True)
            for artifact in staging.iterdir():
                destination = output / artifact.name
                if artifact.is_dir():
                    if destination.exists():
                        shutil.rmtree(destination)
                    shutil.copytree(artifact, destination)
                else:
                    os.replace(artifact, destination)
            manifest.write_text(json.dumps(targets, indent=2) + '\n')
        # Use the symbolizer from the selected toolchain, rather than the older
        # one precompile_swift copied from the upstream builder.
        symbolizer = shutil.which('llvm-symbolizer')
        if symbolizer:
            shutil.copyfile(symbolizer, output / 'llvm-symbolizer')
            (output / 'llvm-symbolizer').chmod(0o755)
        print('Exported fuzz targets: ' + ', '.join(entry['target'] for entry in targets))

    if __name__ == '__main__':
        try:
            source = Path(os.environ.get('SRC', '/src'))
            config = json.loads((source / 'swift-fuzz-config.json').read_text())
            build(config, source, Path(os.environ.get('OUT', '/out')), Path(os.environ.get('WORK', '/work')))
        except (ValueError, OSError, subprocess.SubprocessError, configparser.Error) as error:
            sys.exit('swift-fuzz export: ' + str(error))
    """# + "\n"
}
