import Foundation

enum OSSFuzzTemplates {
    static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    static func jsonQuote(_ value: String) -> String {
        String(decoding: try! JSONEncoder().encode(value), as: UTF8.self)
    }

    static let buildScript = #"""
    #!/bin/bash
    set -euo pipefail
    # Maintainer-owned: add native-library builds or resource copies here.
    . precompile_swift
    python3 "$SRC/swift-fuzz-build.py"
    """# + "\n"

    static func dockerfile(repository: String, checkout: String, swiftImage: String) -> String {
        """
        # Maintainer-owned. The Swift toolchain is independent of OSS-Fuzz's version.
        ARG SWIFT_IMAGE=\(swiftImage)
        FROM ${SWIFT_IMAGE} AS swift-toolchain
        FROM gcr.io/oss-fuzz-base/base-builder-swift:ubuntu-24-04

        COPY --from=swift-toolchain /usr /opt/swift/usr
        ENV PATH="/opt/swift/usr/bin:${PATH}"
        RUN swift --version

        # Install project-specific native dependencies here.
        RUN git clone --depth 1 -- \(shellQuote(repository)) \(shellQuote("/src/" + checkout))
        COPY build.sh swift-fuzz-build.py swift-fuzz-config.json $SRC/
        WORKDIR /src/\(checkout)

        """
    }

    static func projectYAML(repository: String, contact: String, sanitizers: [String]) -> String {
        """
        homepage: \(jsonQuote(repository))
        main_repo: \(jsonQuote(repository))
        language: swift
        base_os_version: ubuntu-24-04
        primary_contact: \(jsonQuote(contact))\(contact.isEmpty ? " # Fill in your OSS-Fuzz contact email" : "")
        fuzzing_engines:
          - libfuzzer
        architectures:
          - x86_64
        sanitizers:
        \(sanitizers.map { "  - " + $0 }.joined(separator: "\n"))

        """
    }

    static let validationScript = #"""
    #!/bin/bash
    # Generated by swift-fuzz. Run from an OSS-Fuzz checkout.
    set -euo pipefail
    project=${1:?Usage: bash projects/PROJECT/validate.sh PROJECT}
    test -f infra/helper.py || { echo 'Run from the root of an OSS-Fuzz checkout.' >&2; exit 1; }
    sanitizers=$(python3 - "$project" <<'PY'
    import sys, yaml
    with open('projects/' + sys.argv[1] + '/project.yaml') as stream:
        config = yaml.safe_load(stream)
    if not config.get('primary_contact'):
        sys.exit('Fill in primary_contact before submission.')
    values = config.get('sanitizers', ['address'])
    if not values or any(value not in ('address', 'thread') for value in values):
        sys.exit('Swift supports address and thread; coverage is tested separately.')
    print(' '.join(values))
    PY
    )
    python3 infra/helper.py build_image "$project"
    for sanitizer in $sanitizers; do
      python3 infra/helper.py build_fuzzers --sanitizer "$sanitizer" --clean "$project"
      python3 infra/helper.py check_build --sanitizer "$sanitizer" "$project"
    done
    python3 infra/helper.py build_fuzzers --sanitizer coverage --clean "$project"
    python3 - "$project" <<'PY'
    import hashlib, json, pathlib, sys, zipfile
    output = pathlib.Path('build/out') / sys.argv[1]
    for entry in json.loads((output / 'swift-fuzz-targets.json').read_text()):
        target = entry['target']
        corpus = pathlib.Path('build/corpus') / sys.argv[1] / target
        corpus.mkdir(parents=True, exist_ok=True)
        archive = output / (target + '_seed_corpus.zip')
        if archive.exists():
            with zipfile.ZipFile(archive) as seeds:
                for name in seeds.namelist():
                    data = seeds.read(name)
                    (corpus / hashlib.sha256(data).hexdigest()).write_bytes(data)
        # Targets without seeds still need one input to exercise their body.
        if not any(corpus.iterdir()):
            (corpus / hashlib.sha256(b'').hexdigest()).write_bytes(b'')
    PY
    # Coverage also exercises seed packaging and source mapping in base-runner.
    python3 infra/helper.py coverage --no-corpus-download --no-serve --port '' "$project"
    python3 - "$project" <<'PY'
    import json, pathlib, sys
    output = pathlib.Path('build/out') / sys.argv[1]
    for entry in json.loads((output / 'swift-fuzz-targets.json').read_text()):
        target = entry['target']
        stats = output / 'fuzzer_stats' / (target + '.json')
        errors = output / 'fuzzer_stats' / (target + '_error.log')
        if errors.exists() or not stats.exists() or not json.loads(stats.read_text()).get('data'):
            sys.exit('Coverage failed for ' + target + '; inspect build/out/' + sys.argv[1] + '/logs.')
    PY
    """# + "\n"

    static let readme = #"""
    # OSS-Fuzz setup

    The generated Dockerfile installs a pinned official Swift toolchain over
    the Ubuntu 24.04 OSS-Fuzz Swift builder. It does not wait for OSS-Fuzz to
    update its compiler. The default is Swift 6.3.3 for paired C-shim targets.
    Standalone targets need a pinned Swift 6.4 Ubuntu 24.04 image; choose it with
    --swift-image on initial generation or change SWIFT_IMAGE in Dockerfile.
    The initial project supports x86_64 and address sanitizer. Thread sanitizer
    is opt-in with --sanitizers address,thread and must pass validation too.

    ## Customize and submit

    1. Fill in primary_contact in project.yaml. Keep any additional contacts there.
    2. Add native dependencies in Dockerfile and custom build/resource steps in build.sh.
       The builder preserves the repository's directory name under /src so local
       SwiftPM dependency identities remain valid. Dependencies outside that repository need
       explicit checkouts. Only files exported to /out are available on fuzzing bots.
    3. Copy Dockerfile, project.yaml, build.sh, swift-fuzz-build.py,
       swift-fuzz-config.json and validate.sh into projects/PROJECT in google/oss-fuzz.
    4. From the OSS-Fuzz checkout, run:

       bash projects/PROJECT/validate.sh PROJECT

    This builds the image, checks every advertised sanitizer in the real runner,
    and builds/runs coverage using the packaged seeds. It requires Docker and the
    OSS-Fuzz helper's Python dependencies. These are container builds, not local
    SwiftPM builds. Fix all errors before submitting the project directory as a PR.

    For a quick individual check after an address build:

       python3 infra/helper.py run_fuzzer PROJECT TARGET -runs=100

    Use a maintained project with an established OSS-Fuzz contact. Acceptance is
    decided by OSS-Fuzz. No submission or message is sent by this command.

    ## Target and input layout

    The build discovers logical registrations from each product. Each logical
    target gets its own native executable, selected by its executable basename;
    no shell or Python launcher is needed on the bot. Explicit FUZZ_TARGET still
    overrides selection for manual use. Names must be unique ignoring ASCII case.

    Seeds/TARGET is packaged by default; Corpus/TARGET is included only when the
    setup command uses --include-corpus. Nested files are supported, duplicate
    contents are deduplicated, and archive entries use content hashes so duplicate
    basenames cannot collide. Empty files are valid seeds; hidden placeholder files
    and symlinks are skipped. Old archives are replaced, never appended to.

    Dictionaries/TARGET.dict is copied when present. Options/TARGET.options can
    customize the OSS-Fuzz options; defaults enable value profiling and disable
    libFuzzer's leak checking, matching local swift-fuzz runs. Other sanitizer
    settings remain under OSS-Fuzz's control. SwiftPM resource bundles are copied
    alongside the binaries. Add any other runtime assets to /out in build.sh.

    swift-fuzz-targets.json in /out records the product-to-target mapping. The
    exporter removes its own stale target files on subsequent successful exports.
    Minimize or restore corpus snapshots using OSS-Fuzz's corpus tools; the source
    repository never needs the accumulated working corpus.

    ## Regeneration

    Re-run the package command after adding/removing executable products or
    changing the package location. Registrations inside existing products are
    discovered on every build, so those changes need no regeneration.

    Dockerfile, project.yaml and build.sh are initialized once and then preserved.
    Options such as --contact and --swift-image only initialize missing files;
    edit existing configuration explicitly. Generated helpers, config, this README
    and validate.sh are refreshed. Edits to generated files are detected and cause
    a refusal instead of being overwritten. Keep .swift-fuzz-generated.json in the
    original setup directory to enable safe regeneration; it is not submitted.
    For an older integration without that state file, generate into a new --output
    directory and migrate the customizations.
    """# + "\n"

    static func normalizeRemote(_ remote: String) -> String? {
        var value = remote.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty, !value.contains(where: { $0.isWhitespace || $0 == "\0" }) else { return nil }
        if value.hasPrefix("ssh://") {
            guard let ssh = URLComponents(string: value), let host = ssh.host,
                  ssh.password == nil, ssh.port == nil || ssh.port == 22 else { return nil }
            value = "https://" + host + ssh.percentEncodedPath
        } else if !value.contains("://"), let at = value.firstIndex(of: "@") {
            let rest = value[value.index(after: at)...]
            guard let colon = rest.firstIndex(of: ":") else { return nil }
            value = "https://" + rest[..<colon] + "/" + rest[rest.index(after: colon)...]
        }
        guard var url = URLComponents(string: value), url.scheme == "https",
              let host = url.host, !host.isEmpty, url.user == nil, url.password == nil,
              url.query == nil, url.fragment == nil, !url.path.isEmpty, url.path != "/" else { return nil }
        while url.path.hasSuffix("/") { url.path.removeLast() }
        if url.path.hasSuffix(".git") { url.path.removeLast(4) }
        guard !url.path.isEmpty, url.path != "/" else { return nil }
        return url.url?.absoluteString
    }

    static func checkoutName(for repository: String) throws -> String {
        let name = URL(string: repository)?.lastPathComponent ?? ""
        let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-")
        guard !name.isEmpty, name != ".", name != "..", name.unicodeScalars.allSatisfy(allowed.contains) else {
            throw OSSFuzzError("The repository URL must end in a portable checkout directory name.")
        }
        return name
    }
}
